### ISSUE TITLE
Algorithm translation

### ISSUE THREAD

**Issue by SharhadBashar** [Aawesh/AdaBoost.M1#1]
I am trying to understand the translation between the algorithm in your pdf report and the python code
1. where are you calculating the error and then aborting the loop if error > 0.5
2. where are you doing step 4 of the algorithm (beta = error/(1 - error))
3. where is your Zt, the normalization constant
4. where are you doing the final hypothesis?
5. the algo says do t = 1, 2, ... T: is this T the same as m in the code?

**Comment by Aawesh** [comment]
I would recommend running the python code and understand the code line by line. A single line of code doing a lot of stuff there. The code might not look like the algorithm at a glance. Here, the goal is to see how to visualize the error.

**Comment by Aawesh** [comment]
Not an issue
